services:
  django:
    container_name: devmasters_django
    build:
      context: .
      dockerfile: compose/local/django/Dockerfile
    restart: unless-stopped
    env_file:
      - .envs/.local/.django
      - .envs/.local/.postgres
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    command: bash /start
    volumes:
      - local_static_volume:/app/static
      - local_media_volume:/app/media
      - .:/app

  postgres:
    container_name: devmasters_postgres
    image: postgres:16.3
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
    env_file:
      - .envs/.local/.postgres
    ports:
      - "5437:5432"
    expose:
      - "5437"


volumes:
  local_postgres_data:
  local_static_volume:
  local_media_volume:
