#!/bin/sh


echo 'Running migrations...'
python manage.py migrate


echo 'Collecting static files...'
python manage.py collectstatic --no-input

echo 'Running server...'
gunicorn config.wsgi:application -b 0.0.0.0:8000
